/** The full base-tier collection, generated from the pocket_knights_cards
 *  export: real ids, real names, real rarities. Slot decides the archetype
 *  (Weapon -> attack, Off-Hand -> block, else heal). */
import type { Gear } from './types.js';

export const GEAR: Gear[] = [
  {
    id: 'Hero-Weapon-Common-Base',
    cls: 'Hero',
    name: 'Short Sword',
    rarity: 'Common',
    effect: 'attack',
    slot: 'Weapon',
    power: 8,
  },
  {
    id: 'Hero-Weapon-Rare-Base',
    cls: 'Hero',
    name: 'Crystal Sword',
    rarity: 'Rare',
    effect: 'attack',
    slot: 'Weapon',
    power: 12,
  },
  {
    id: 'Hero-Weapon-Epic-Base',
    cls: 'Hero',
    name: 'Blessed Hammer',
    rarity: 'Epic',
    effect: 'attack',
    slot: 'Weapon',
    power: 16,
  },
  {
    id: 'Hero-Off-Hand-Common-Base',
    cls: 'Hero',
    name: 'Bladed Shield',
    rarity: 'Common',
    effect: 'block',
    slot: 'Off-Hand',
    power: 8,
  },
  {
    id: 'Hero-Off-Hand-Rare-Base',
    cls: 'Hero',
    name: 'Tower Shield',
    rarity: 'Rare',
    effect: 'block',
    slot: 'Off-Hand',
    power: 13,
  },
  {
    id: 'Hero-Off-Hand-Epic-Base',
    cls: 'Hero',
    name: 'Charged Whetstone',
    rarity: 'Epic',
    effect: 'block',
    slot: 'Off-Hand',
    power: 18,
  },
  {
    id: 'Hero-Chest-Common-Base',
    cls: 'Hero',
    name: 'Breastplate',
    rarity: 'Common',
    effect: 'effect',
    slot: 'Chest',
    power: 2,
  },
  {
    id: 'Hero-Chest-Rare-Base',
    cls: 'Hero',
    name: 'Full Plate',
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Chest',
    power: 4,
  },
  {
    id: 'Hero-Chest-Epic-Base',
    cls: 'Hero',
    name: 'Galvanic Plate',
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Chest',
    power: 6,
  },
  {
    id: 'Hero-Hat-Common-Base',
    cls: 'Hero',
    name: 'Leather Helm',
    rarity: 'Common',
    effect: 'effect',
    slot: 'Hat',
    power: 2,
  },
  {
    id: 'Hero-Hat-Rare-Base',
    cls: 'Hero',
    name: 'Shadow Helm',
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Hat',
    power: 4,
  },
  {
    id: 'Hero-Hat-Epic-Base',
    cls: 'Hero',
    name: "Knight's Helm",
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Hat',
    power: 6,
  },
  {
    id: 'Hero-Necklace-Common-Base',
    cls: 'Hero',
    name: "Warrior's Crest",
    rarity: 'Common',
    effect: 'effect',
    slot: 'Necklace',
    power: 4,
  },
  {
    id: 'Hero-Necklace-Rare-Base',
    cls: 'Hero',
    name: 'Swift Crest',
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Necklace',
    power: 6,
  },
  {
    id: 'Hero-Necklace-Epic-Base',
    cls: 'Hero',
    name: 'Dragon Crest',
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Necklace',
    power: 8,
  },
  {
    id: 'Hero-Weapon-Legendary-Base',
    cls: 'Hero',
    name: 'Lightning Bolt',
    rarity: 'Legendary',
    effect: 'attack',
    slot: 'Weapon',
    power: 19,
  },
  {
    id: 'Archer-Weapon-Common-Base',
    cls: 'Archer',
    name: 'Shortbow',
    rarity: 'Common',
    effect: 'attack',
    slot: 'Weapon',
    power: 9,
  },
  {
    id: 'Archer-Weapon-Rare-Base',
    cls: 'Archer',
    name: "Hunter's Arbalest",
    rarity: 'Rare',
    effect: 'attack',
    slot: 'Weapon',
    power: 13,
  },
  {
    id: 'Archer-Weapon-Epic-Base',
    cls: 'Archer',
    name: 'Zephyr Bow',
    rarity: 'Epic',
    effect: 'attack',
    slot: 'Weapon',
    power: 17,
  },
  {
    id: 'Archer-Off-Hand-Common-Base',
    cls: 'Archer',
    name: "Ranger's Quiver",
    rarity: 'Common',
    effect: 'block',
    slot: 'Off-Hand',
    power: 7,
  },
  {
    id: 'Archer-Off-Hand-Rare-Base',
    cls: 'Archer',
    name: 'Iron Quiver',
    rarity: 'Rare',
    effect: 'block',
    slot: 'Off-Hand',
    power: 11,
  },
  {
    id: 'Archer-Off-Hand-Epic-Base',
    cls: 'Archer',
    name: 'Infinite Quiver',
    rarity: 'Epic',
    effect: 'block',
    slot: 'Off-Hand',
    power: 15,
  },
  {
    id: 'Archer-Chest-Common-Base',
    cls: 'Archer',
    name: 'Leather Cuirass',
    rarity: 'Common',
    effect: 'effect',
    slot: 'Chest',
    power: 3,
  },
  {
    id: 'Archer-Chest-Rare-Base',
    cls: 'Archer',
    name: 'Vernal Cloak',
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Chest',
    power: 5,
  },
  {
    id: 'Archer-Chest-Epic-Base',
    cls: 'Archer',
    name: 'Sylvan Plate',
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Chest',
    power: 7,
  },
  {
    id: 'Archer-Hat-Common-Base',
    cls: 'Archer',
    name: 'Feathered Cap',
    rarity: 'Common',
    effect: 'effect',
    slot: 'Hat',
    power: 3,
  },
  {
    id: 'Archer-Hat-Rare-Base',
    cls: 'Archer',
    name: "Marksman's Scope",
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Hat',
    power: 5,
  },
  {
    id: 'Archer-Hat-Epic-Base',
    cls: 'Archer',
    name: 'Blitz Bandanna',
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Hat',
    power: 7,
  },
  {
    id: 'Archer-Necklace-Common-Base',
    cls: 'Archer',
    name: 'Rabbit Talisman',
    rarity: 'Common',
    effect: 'effect',
    slot: 'Necklace',
    power: 5,
  },
  {
    id: 'Archer-Necklace-Rare-Base',
    cls: 'Archer',
    name: 'Lizard Talisman',
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Necklace',
    power: 7,
  },
  {
    id: 'Archer-Necklace-Epic-Base',
    cls: 'Archer',
    name: 'Eagle Talisman',
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Necklace',
    power: 9,
  },
  {
    id: 'Archer-Weapon-Legendary-Base',
    cls: 'Archer',
    name: 'Artemial Arcbow',
    rarity: 'Legendary',
    effect: 'attack',
    slot: 'Weapon',
    power: 18,
  },
  {
    id: 'Mage-Weapon-Common-Base',
    cls: 'Mage',
    name: "Mage's Staff",
    rarity: 'Common',
    effect: 'attack',
    slot: 'Weapon',
    power: 7,
  },
  {
    id: 'Mage-Weapon-Rare-Base',
    cls: 'Mage',
    name: 'Flame Staff',
    rarity: 'Rare',
    effect: 'attack',
    slot: 'Weapon',
    power: 11,
  },
  {
    id: 'Mage-Weapon-Epic-Base',
    cls: 'Mage',
    name: 'Frost Staff',
    rarity: 'Epic',
    effect: 'attack',
    slot: 'Weapon',
    power: 15,
  },
  {
    id: 'Mage-Off-Hand-Common-Base',
    cls: 'Mage',
    name: 'Arcane Tome',
    rarity: 'Common',
    effect: 'block',
    slot: 'Off-Hand',
    power: 6,
  },
  {
    id: 'Mage-Off-Hand-Rare-Base',
    cls: 'Mage',
    name: 'Frozen Tome',
    rarity: 'Rare',
    effect: 'block',
    slot: 'Off-Hand',
    power: 10,
  },
  {
    id: 'Mage-Off-Hand-Epic-Base',
    cls: 'Mage',
    name: 'Infernal Tome',
    rarity: 'Epic',
    effect: 'block',
    slot: 'Off-Hand',
    power: 14,
  },
  {
    id: 'Mage-Chest-Common-Base',
    cls: 'Mage',
    name: "Novice's Robes",
    rarity: 'Common',
    effect: 'effect',
    slot: 'Chest',
    power: 3,
  },
  {
    id: 'Mage-Chest-Rare-Base',
    cls: 'Mage',
    name: 'Glacial Robes',
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Chest',
    power: 5,
  },
  {
    id: 'Mage-Chest-Epic-Base',
    cls: 'Mage',
    name: 'Scintillating Robes',
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Chest',
    power: 7,
  },
  {
    id: 'Mage-Hat-Common-Base',
    cls: 'Mage',
    name: "Wizard's Hat",
    rarity: 'Common',
    effect: 'effect',
    slot: 'Hat',
    power: 3,
  },
  {
    id: 'Mage-Hat-Rare-Base',
    cls: 'Mage',
    name: 'Smoldering Hat',
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Hat',
    power: 5,
  },
  {
    id: 'Mage-Hat-Epic-Base',
    cls: 'Mage',
    name: 'Icicle Hat',
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Hat',
    power: 7,
  },
  {
    id: 'Mage-Necklace-Common-Base',
    cls: 'Mage',
    name: "Mage's Amulet",
    rarity: 'Common',
    effect: 'effect',
    slot: 'Necklace',
    power: 5,
  },
  {
    id: 'Mage-Necklace-Rare-Base',
    cls: 'Mage',
    name: 'Molten Amulet',
    rarity: 'Rare',
    effect: 'effect',
    slot: 'Necklace',
    power: 7,
  },
  {
    id: 'Mage-Necklace-Epic-Base',
    cls: 'Mage',
    name: 'Frostbite Amulet',
    rarity: 'Epic',
    effect: 'effect',
    slot: 'Necklace',
    power: 9,
  },
  {
    id: 'Mage-Weapon-Legendary-Base',
    cls: 'Mage',
    name: 'Tempest Staff',
    rarity: 'Legendary',
    effect: 'attack',
    slot: 'Weapon',
    power: 17,
  },
];
